name: test 
on:
 push:
 workflow_dispatch: 
jobs:
  build:
    continue-on-error: true
    strategy: 
      matrix:
        node-version:  [12 13 14]
        operting-system: [ubantu-version, windows-version]
    runs-on: ${{matrix.operting-system}}
    steps: 
      - name: Get code 
        uses: actions/checkout@v3
      - name: install nodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: npm ci 
      - name: build project 
        run: npm run build
